### POST request to create new patient
POST http://lb-181d3d6e.elb.localhost.localstack.cloud:4004/api/patients/create-patient
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Doe Kafka Testtttt",
  "email": "email@gmail.com",
  "address": "123 main street",
  "dateOfBirth": "1998-11-23",
  "registeredDate": "2026-02-05"
}
###