### POST request to create new patient
POST http://localhost:4000/api/patients/create-patient
Content-Type: application/json

{
  "name": "John Doe",
  "email": "email@gmail.com",
  "address": "123 main street",
  "dateOfBirth": "1998-11-23",
  "registeredDate": "2026-02-05"
}
###