### PUT request to update an existing patient
PUT http://localhost:4000/api/patients/update-patient/1533dda4-4428-4b5c-ba64-4eec97f0e706
Content-Type: application/json

{
  "name": "John Doe",
  "email": "email@gmail.com",
  "address": "123 main street",
  "dateOfBirth": "1998-11-23",
  "registeredDate": "2026-02-05"
}
###